version: "1.0"

services:
  appservice:
    build: ./deploy
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/project_umbrella?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

    ports:
      - 8085:8080

    networks:
      - springnet

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3333:3306

    networks:
      - springnet

networks:
  springnet: