version: "3.8"

services:
  frontend:
    image: rudra708/analytx-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - springnet

  backend:
    image: rudra708/analytx-backend
    container_name: backend
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/project_umbrella?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    networks:
      - springnet

  database:
    image: mysql
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3333:3306"
    networks:
      - springnet

networks:
  springnet:
